"""add_tenant_brand_hotel_tables

Revision ID: 3d2c78a8db67
Revises: 309019e8ac86
Create Date: 2026-03-25 15:27:47.865223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d2c78a8db67'
down_revision: Union[str, Sequence[str], None] = '309019e8ac86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
