"""add_featured_testimonials_hero_slides_tenant_social

Revision ID: 49b68cba4242
Revises: f61345e4918f
Create Date: 2026-03-29 07:29:33.877837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49b68cba4242'
down_revision: Union[str, Sequence[str], None] = 'f61345e4918f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hero_slides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('headline', sa.String(), nullable=False),
    sa.Column('subline', sa.String(), nullable=True),
    sa.Column('link_url', sa.String(), nullable=True),
    sa.Column('link_label', sa.String(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hero_slides_id'), 'hero_slides', ['id'], unique=False)
    op.create_index(op.f('ix_hero_slides_tenant_id'), 'hero_slides', ['tenant_id'], unique=False)
    op.create_table('testimonials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('author_name', sa.String(), nullable=False),
    sa.Column('author_tag', sa.String(), nullable=True),
    sa.Column('quote', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_testimonials_id'), 'testimonials', ['id'], unique=False)
    op.create_index(op.f('ix_testimonials_tenant_id'), 'testimonials', ['tenant_id'], unique=False)
    op.add_column('hotels', sa.Column('is_featured', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('tenants', sa.Column('contact_phone', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('social_instagram', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('social_facebook', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('social_line', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'social_line')
    op.drop_column('tenants', 'social_facebook')
    op.drop_column('tenants', 'social_instagram')
    op.drop_column('tenants', 'contact_phone')
    op.drop_column('hotels', 'is_featured')
    op.drop_index(op.f('ix_testimonials_tenant_id'), table_name='testimonials')
    op.drop_index(op.f('ix_testimonials_id'), table_name='testimonials')
    op.drop_table('testimonials')
    op.drop_index(op.f('ix_hero_slides_tenant_id'), table_name='hero_slides')
    op.drop_index(op.f('ix_hero_slides_id'), table_name='hero_slides')
    op.drop_table('hero_slides')
    # ### end Alembic commands ###
