"""add_confirmation_code_to_reservation

Revision ID: 664291a6b26c
Revises: f297d82f9384
Create Date: 2026-03-28 20:48:02.846797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '664291a6b26c'
down_revision: Union[str, Sequence[str], None] = 'f297d82f9384'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('confirmation_code', sa.String(length=12), nullable=True))
    op.create_index(op.f('ix_reservations_confirmation_code'), 'reservations', ['confirmation_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reservations_confirmation_code'), table_name='reservations')
    op.drop_column('reservations', 'confirmation_code')
    # ### end Alembic commands ###
