"""add_tenant_social_testimonials_heroslides

Revision ID: a3967fb3e3aa
Revises: 49b68cba4242
Create Date: 2026-03-29 12:43:55.839497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3967fb3e3aa'
down_revision: Union[str, Sequence[str], None] = '49b68cba4242'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('contact_phone', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('social_instagram', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('social_facebook', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('social_line', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'social_line')
    op.drop_column('tenants', 'social_facebook')
    op.drop_column('tenants', 'social_instagram')
    op.drop_column('tenants', 'contact_phone')
    # ### end Alembic commands ###
