"""add_hotel_id_to_business_tables

Revision ID: c117eac7c80f
Revises: 3d2c78a8db67
Create Date: 2026-03-25 15:29:39.572017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c117eac7c80f'
down_revision: Union[str, Sequence[str], None] = '3d2c78a8db67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('folios', sa.Column('hotel_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_folios_hotel_id'), 'folios', ['hotel_id'], unique=False)
    op.add_column('guests', sa.Column('hotel_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_guests_id_number'), table_name='guests')
    op.create_index(op.f('ix_guests_id_number'), 'guests', ['id_number'], unique=False)
    op.create_index(op.f('ix_guests_hotel_id'), 'guests', ['hotel_id'], unique=False)
    op.add_column('reservations', sa.Column('hotel_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_reservations_hotel_id'), 'reservations', ['hotel_id'], unique=False)
    op.add_column('room_types', sa.Column('hotel_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_room_types_hotel_id'), 'room_types', ['hotel_id'], unique=False)
    op.add_column('rooms', sa.Column('hotel_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_rooms_hotel_id'), 'rooms', ['hotel_id'], unique=False)
    op.add_column('users', sa.Column('hotel_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('brand_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('tenant_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tenant_id')
    op.drop_column('users', 'brand_id')
    op.drop_column('users', 'hotel_id')
    op.drop_index(op.f('ix_rooms_hotel_id'), table_name='rooms')
    op.drop_column('rooms', 'hotel_id')
    op.drop_index(op.f('ix_room_types_hotel_id'), table_name='room_types')
    op.drop_column('room_types', 'hotel_id')
    op.drop_index(op.f('ix_reservations_hotel_id'), table_name='reservations')
    op.drop_column('reservations', 'hotel_id')
    op.drop_index(op.f('ix_guests_hotel_id'), table_name='guests')
    op.drop_index(op.f('ix_guests_id_number'), table_name='guests')
    op.create_index(op.f('ix_guests_id_number'), 'guests', ['id_number'], unique=1)
    op.drop_column('guests', 'hotel_id')
    op.drop_index(op.f('ix_folios_hotel_id'), table_name='folios')
    op.drop_column('folios', 'hotel_id')
    # ### end Alembic commands ###
