"""add_hotel_roomtype_images_amenities_fields

Revision ID: fa775435e906
Revises: f3de7f29073c
Create Date: 2026-03-26 21:30:31.509418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa775435e906'
down_revision: Union[str, Sequence[str], None] = 'f3de7f29073c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_type_amenities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['room_type_id'], ['room_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_type_amenities_id'), 'room_type_amenities', ['id'], unique=False)
    op.create_index(op.f('ix_room_type_amenities_room_type_id'), 'room_type_amenities', ['room_type_id'], unique=False)
    op.create_table('room_type_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_type_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('alt_text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['room_type_id'], ['room_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_type_images_id'), 'room_type_images', ['id'], unique=False)
    op.create_index(op.f('ix_room_type_images_room_type_id'), 'room_type_images', ['room_type_id'], unique=False)
    op.create_table('hotel_amenities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hotel_amenities_hotel_id'), 'hotel_amenities', ['hotel_id'], unique=False)
    op.create_index(op.f('ix_hotel_amenities_id'), 'hotel_amenities', ['id'], unique=False)
    op.create_table('hotel_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('alt_text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hotel_images_hotel_id'), 'hotel_images', ['hotel_id'], unique=False)
    op.create_index(op.f('ix_hotel_images_id'), 'hotel_images', ['id'], unique=False)
    op.add_column('hotels', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('hotels', sa.Column('region', sa.String(), nullable=True))
    op.add_column('hotels', sa.Column('license_number', sa.String(), nullable=True))
    op.add_column('hotels', sa.Column('check_in_time', sa.String(), nullable=True))
    op.add_column('hotels', sa.Column('check_out_time', sa.String(), nullable=True))
    op.add_column('room_types', sa.Column('room_code', sa.String(), nullable=True))
    op.add_column('room_types', sa.Column('bed_type', sa.String(), nullable=True))
    op.add_column('room_types', sa.Column('has_window', sa.Boolean(), nullable=True))
    op.add_column('room_types', sa.Column('size_sqm', sa.Numeric(precision=6, scale=1), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room_types', 'size_sqm')
    op.drop_column('room_types', 'has_window')
    op.drop_column('room_types', 'bed_type')
    op.drop_column('room_types', 'room_code')
    op.drop_column('hotels', 'check_out_time')
    op.drop_column('hotels', 'check_in_time')
    op.drop_column('hotels', 'license_number')
    op.drop_column('hotels', 'region')
    op.drop_column('hotels', 'phone')
    op.drop_index(op.f('ix_hotel_images_id'), table_name='hotel_images')
    op.drop_index(op.f('ix_hotel_images_hotel_id'), table_name='hotel_images')
    op.drop_table('hotel_images')
    op.drop_index(op.f('ix_hotel_amenities_id'), table_name='hotel_amenities')
    op.drop_index(op.f('ix_hotel_amenities_hotel_id'), table_name='hotel_amenities')
    op.drop_table('hotel_amenities')
    op.drop_index(op.f('ix_room_type_images_room_type_id'), table_name='room_type_images')
    op.drop_index(op.f('ix_room_type_images_id'), table_name='room_type_images')
    op.drop_table('room_type_images')
    op.drop_index(op.f('ix_room_type_amenities_room_type_id'), table_name='room_type_amenities')
    op.drop_index(op.f('ix_room_type_amenities_id'), table_name='room_type_amenities')
    op.drop_table('room_type_amenities')
    # ### end Alembic commands ###
